ITU.RefereeAssistant.Web/Models/TournamentType.cs
using ITU.RefereeAssistant.Domain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ITU.RefereeAssistant.Web.Models
{
    public class TournamentType : IEntity
    {
        public virtual long Id { get; set; }
        public virtual string Name { get; set; }
        public virtual string TypeName { get; set; }
    }
}

ITU.RefereeAssistant.Web/Controllers/TournamentController.cs
using ITU.RefereeAssistant.BL;
using ITU.RefereeAssistant.Domain.Models;
using ITU.RefereeAssistant.Domain.TourType;
using ITU.RefereeAssistant.Web.Extensions;
using ITU.RefereeAssistant.Web.Models;
using ITU.RefereeAssistant.Web.Services;
using NHibernate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ITU.RefereeAssistant.Web.Controllers
{
    [Authorize]
    public class TournamentController : Controller
    {
        private PlayerService PlayerService = new PlayerService();
        private Services.TournamentService TournamentService = new Services.TournamentService();
        private BaseService<Round> RoundService = new BaseService<Round>();
        private BaseService<Domain.TournamentType> TournamentTypeService = new BaseService<Domain.TournamentType>();
        [HttpGet]
        public ActionResult Start()
        {
            var model = new TournamentStarter();           
            model.Players = PlayerService.GetAll();
            var types = TournamentTypeService.GetAll();
            var selectList = new SelectList(types, "Id", "Name");
            model.tournamentTypes = selectList;
            return View(model);
        }
        [HttpPost]
        public ActionResult Start(TournamentStarter starter)
        {
            if (ModelState.IsValid)
            {
                if (starter.Players.Any())
                {
                    foreach (var player in starter.Players)
                    {
                        PlayerService.Save(player);
                    }
                }

                var dbTourType = TournamentTypeService.Get(starter.TournamentType.Id);
                var tourTypes = Helper.LoadTournamentTypes(AppDomain.CurrentDomain.BaseDirectory + @"bin\");
                var tourType = tourTypes.FirstOrDefault(
                    item => item.GetType().FullName == dbTourType.TypeName);
                tourType.players = starter.Players;
                var ts = new BL.TournamentService();
                ts.TourType = tourType;
                var tour = ts.Create(starter.Players.ToArray(), dbTourType, User.Identity.Name, starter.Description);
                var round = ts.GenerateRound(tour);
                TournamentService.Save(tour);
                return RedirectToAction("Details", "Round", new { Id = round.Id });
            }
            return View(starter);
        }
        public ActionResult Delete(Player player)
        {
            PlayerService.Delete(player);
            return RedirectToAction("Start");
        }
        public ActionResult Add(Player player)
        {
            PlayerService.Save(player);
            return RedirectToAction("Start");
        }
        [HttpGet]        
        public ActionResult Overview()
        {
            var model = new TournamentOverview();
            model.Tournaments = TournamentService.GetAll();            
            return View(model);
        }
        [HttpGet]
        public ActionResult ShowLastRound(long Id)
        {
            Tournament tour = TournamentService.Get(Id);
            int maxOrderNum = tour.Rounds.Max(r => r.OrderNum);
            long lastRoundId = tour.Rounds.SingleOrDefault(r => r.OrderNum == maxOrderNum).Id;            
            return RedirectToAction("Details", "Round", new { Id=lastRoundId});
        }        
    }
}

ITU.RefereeAssistant.Web/Views/Shared/Match.cshtml
@model ITU.RefereeAssistant.Domain.Models.Match
@{
    var count = ViewData["count"];
}
<input class="btn btn-link" type="button" value="@Model.FirstPlayer" />
<i>VS</i>
<input class="btn btn-link" type="button" value="@Model.SecondPlayer" />

@Html.EditorFor(item => item.MatchResult)

<script>
    function MatchResultSend@(count)(matchResult) {
        $.ajax({
            url: "/Round/SaveMatchResult",
            type: "POST",
            cache: false,
            data: {
                id: @(Model.Id),
                matchResult: $(matchResult).val()
            },
            success: function (result) {
                console.log(result)
            }
        });
    }
</script>

ITU.RefereeAssistant.Web/Views/Shared/RoundNavigation.cshtml
@model ITU.RefereeAssistant.Domain.Models.Round

<div class="btn-toolbar" role="toolbar" aria-label="RoundNavigation">
    <div class="btn-group btn-group-sm" role="group" aria-label="PrevRounds">
        @{
            foreach (var item in Model.Tournament.Rounds.Where(r => r.OrderNum < Model.OrderNum).OrderBy(r => r.OrderNum))
            {                
                <button type="button" class="btn btn-secondary btn-sm" onclick="location.href='@Url.Action("Details", new { Id = item.Id })'">@item.OrderNum</button>
            }
        }
    </div>
    <div class="btn-group btn-group-sm" role="group" aria-label="CurrentRound">
        <button type="button" class="btn btn-secondary btn-sm" disabled>@Model.OrderNum</button>
    </div>
    <div class="btn-group btn-group-sm" role="group" aria-label="PrevRounds">
        @if (Model.Tournament.Rounds.Max(r => r.OrderNum) > Model.OrderNum)
        {
            foreach (var item in Model.Tournament.Rounds.Where(r => r.OrderNum > Model.OrderNum).OrderBy(r => r.OrderNum))
            {                
                <button type="button" class="btn btn-secondary btn-sm" onclick="location.href='@Url.Action("Details", new { Id = item.Id })'">@item.OrderNum</button>
            }
        }
        else
        { 
            <button type="button" class = "btn btn-secondary btn-sm" onclick="location.href='@Url.Action("GenerateNextRound", new { Id = Model.Id })'">Следующий раунд</button>                    
        }
</div>
    
</div>

ITU.RefereeAssistant.Web/Views/Shared/Tournament.cshtml
@model ITU.RefereeAssistant.Domain.Models.Tournament
<div class="row">
    <div class="col-md-8">@Html.DisplayFor(tournament => tournament.Description)</div>
    <div class="col-md-4">
        @Html.ActionLink("Перейти к раундам", "ShowLastRound", "Tournament", new { id = @Model.Id }, "")       
    </div>
</div>

ITU.RefereeAssistant.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")    

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Помошник судьи", "Overview", "Tournament", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>